START TRANSACTION;

DROP TABLE IF EXISTS records CASCADE;

CREATE TABLE IF NOT EXISTS records (
    host_since date,
    host_response_time varchar(30),
    host_response_rate integer,
    host_is_superhost boolean,
    host_has_profile_pic  boolean,
    host_identity_verified boolean,
    neighbourhood varchar(50),
    latitude real,
    longitude real,
    property_type varchar(50),
    room_type varchar(50),
    accommodates integer,
    bathrooms real,
    bedrooms integer,
    beds integer,
    bed_type varchar(30),
    amenities varchar(1500),
    price real,
    security_deposit real,
    cleaning_fee real,
    guests_included integer,
    extra_people real,
    minimum_nights integer,
    maximum_nights integer,
    review_scores_rating real,
    instant_bookable  boolean,
    cancellation_policy varchar(50),
    require_guest_profile_picture boolean,
    month varchar(20),
    kitchen boolean,
    wifi boolean,
    essentials boolean,
    tv boolean,
    air_conditioning boolean,
    elevator boolean,
    washer boolean,
    hangers boolean,
    iron boolean,
    laptop_friendly_workspace boolean,
    family_kid_friendly boolean,
    hot_water boolean,
    cable_tv boolean,
    free_parking_on_premises boolean,
    hair_dryer boolean,
    smoking_allowed boolean,
    doorman boolean,
    dishes_and_silverware boolean,
    buzzer_wireless_intercom boolean,
    refrigerator boolean
);

COMMIT;